apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: mlops
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          ports:
            - containerPort: 5000
          command: ["mlflow"]
          args:
            - "server"
            - "--backend-store-uri"
            - "sqlite:////mlflow/mlruns.db"
            - "--default-artifact-root"
            - "/mlflow/artifacts"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "5000"
          volumeMounts:
            - name: mlflow-vol
              mountPath: /mlflow
      volumes:
        - name: mlflow-vol
          persistentVolumeClaim:
            claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlops
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
